apiVersion: 1
datasources:
  - name: Prometheus
    type: prometheus
    url: http://localhost:9090
    access: proxy
    isDefault: true
    editable: true
  - name: CloudWatch
    type: cloudwatch
    jsonData:
      defaultRegion: eu-central-1
      authType: default
    isDefault: true