server:
  http_listen_port: 9080

clients:
  - url: http://localhost:3100/loki/api/v1/push # Sends data to your local Loki container

scrape_configs:
  - job_name: aws_vpn_logs
    aws_cloudwatch:
      log_group_name: /aws/vpn/dev-client-vpn
      region: eu-central-1
    pipeline_stages:
      # 1. Parse the AWS VPN JSON log
      - json:
          expressions:
            client_ip: 'client-ip' # Extracts the IP address from the log
      
      # 2. Translate the IP into GPS coordinates using the MaxMind DB
      - geoip:
          db: "/etc/promtail/GeoLite2-City.mmdb"
          source: client_ip
          db_type: city

      # 3. Attach the new GPS coordinates as labels to the log!
      - labels:
          geoip_latitude:
          geoip_longitude:
          geoip_country_name: