name: Deploy Workflow

on:
    push:
        branches:
            - main

permissions:
    id-token: write
    contents: read
    security-events: write

jobs:
    deploy:
        runs-on: ubuntu-latest