name: Destroy Workflow

on:
    workflow_dispatch:
        inputs:
            environment:
                description: 'Type "Destroy" to confirm the destruction of the environment'
                required: true
                default: 'NO'

permissions:
    id-token: write
    contents: read
    security-events: write

jobs:
    deploy:
        runs-on: ubuntu-latest